var message = "it's a secret to everybody";
alert(message);
var num = 19;
var newNum = num + 200;
var remainder = 45 % 6;
var newerNum = newNum + remainder;
var product = ((2 * 4) * 4) + (3 * 4);
alert(product);
var name = "Tom Bombadil";
var greeting = "Hello, " + name + "!";
alert(greeting);
var bluesGuitar = prompt("What's your favorite guitar to play the blues on?", "Gibson ES-335");
